# Generated by Django 2.2 on 2021-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='', max_length=45),
        ),
    ]
