# Generated by Django 2.2 on 2021-06-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComm', '0003_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='itemName',
        ),
    ]
