# Generated by Django 2.2 on 2021-06-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComm', '0004_auto_20210610_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
